# Generated by Django 5.2.4 on 2025-07-12 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(default='', max_length=254, null=True, unique=True),
        ),
    ]
