# Generated by Django 5.2.4 on 2025-07-12 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_server', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
