# Generated by Django 5.2.4 on 2025-07-14 06:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_server', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
